---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: compute
  name: compute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute
  template:
    metadata:
      labels:
        app: compute
    spec:
      containers:
      - image: compute
        name: compute
        env:
        - name: LOGGER_DEBUG
          value: "1"
        - name: GRPC_SERVER_PORT
          value: "9000"
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: cloud
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: compute
  name: compute
spec:
  ports:
  - name: http2
    port: 9000
    protocol: TCP
  selector:
    app: compute
  type: ClusterIP
