---
apiVersion: batch/v1
kind: Job
metadata:
  name: compute-automated-test
spec:
  template:
    spec:
      initContainers:
      - image: busybox:1.32
        name: wait-for-compute
        command:
        - sh
        - -c
        - timeout 60 sh -c 'until nc -z $0 $1; do sleep 1; done' compute 9000
      containers:
      - image: compute-automated-test
        name: compute-automated-test
        env:
        - name: LOGGER_DEBUG
          value: "1"
        - name: GRPC_ADDRESS
          value: compute:9000
      restartPolicy: Never
  backoffLimit: 3
