apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rdb
  name: rdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdb
  template:
    metadata:
      labels:
        app: rdb
    spec:
      containers:
      - image: rdb
        name: rdb
