---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resourcemanager
  name: resourcemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourcemanager
  template:
    metadata:
      labels:
        app: resourcemanager
    spec:
      containers:
      - image: resourcemanager
        name: resourcemanager
        env:
        - name: LOGGER_DEBUG
          value: "1"
        - name: GRPC_SERVER_PORT
          value: "9003"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: resourcemanager
  name: resourcemanager
spec:
  ports:
  - name: http2
    port: 9003
    protocol: TCP
  selector:
    app: resourcemanager
  type: ClusterIP
