---
apiVersion: batch/v1
kind: Job
metadata:
  name: resourcemanager-automated-test
spec:
  template:
    spec:
      containers:
      - image: resourcemanager-automated-test
        name: resourcemanager-automated-test
        env:
        - name: LOGGER_DEBUG
          value: "1"
        - name: GRPC_ADDRESS
          value: resourcemanager:9003
      restartPolicy: Never
  backoffLimit: 3
