apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: demo--apps
build:
  artifacts:
  - image: compute
    docker:
      buildArgs:
        cmd: compute
  - image: iam
    docker:
      buildArgs:
        cmd: iam
  - image: rdb
    docker:
      buildArgs:
        cmd: rdb
  - image: resourcemanager
    docker:
      buildArgs:
        cmd: resourcemanager
deploy:
  kustomize:
    paths:
    - deployments/local
