apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: demo--apps
build:
  artifacts:
  - image: authorizer
    docker:
      buildArgs:
        cmd: authorizer
  - image: compute
    docker:
      buildArgs:
        cmd: compute
  - image: compute-automated-test
    docker:
      buildArgs:
        cmd: compute-automated-test
  - image: iam
    docker:
      buildArgs:
        cmd: iam
  - image: iam-automated-test
    docker:
      buildArgs:
        cmd: iam-automated-test
  - image: rdb
    docker:
      buildArgs:
        cmd: rdb
  - image: rdb-automated-test
    docker:
      buildArgs:
        cmd: rdb-automated-test
  - image: resourcemanager
    docker:
      buildArgs:
        cmd: resourcemanager
  - image: resourcemanager-automated-test
    docker:
      buildArgs:
        cmd: resourcemanager-automated-test
deploy:
  kustomize:
    paths:
    - deployments/local
