---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        volumeMounts:
        - name: sql-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: sql-volume
        configMap:
          name: sql-files
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
