name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Make
      run: make
    - name: Diff
      run: git diff --exit-code

  push:
    name: Push
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    strategy:
      matrix:
        app:
        - authorizer
        - compute
        - compute-automated-test
        - iam
        - iam-automated-test
        - rdb
        - rdb-automated-test
        - resourcemanager
        - resourcemanager-automated-test
    steps:
      - uses: actions/checkout@v2
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_NAME=demo20-${{ matrix.app }}
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/demo20-apps/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$GITHUB_SHA

          docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg cmd=${{ matrix.app }}

          docker tag $IMAGE_NAME $IMAGE_ID:$GITHUB_SHA
          docker push $IMAGE_ID:$GITHUB_SHA

  commit:
    name: Commit 
    # needs: push
    runs-on: ubuntu-latest
    # if: github.event_name == 'push'
    steps:
    - run: |
        VALUES=authorizer.tag=${GITHUB_SHA}
        VALUES=${VALUES},compute.tag=${GITHUB_SHA},iam.tag=${GITHUB_SHA},rdb.tag=${GITHUB_SHA},resourcemanager.tag=${GITHUB_SHA}
        VALUES=${VALUES},computeautomatedtest.tag=${GITHUB_SHA},iamautomatedtest.tag=${GITHUB_SHA},rdbautomatedtest=${GITHUB_SHA},resourcemanagerautomatedtest.tag=${GITHUB_SHA}

        docker run \
          -e VALUES=${VALUES}\
          -e VALUES_FILE=apps/values.yaml\
          -e DRY_RUN=1\
          -e GIT_MESSAGE="Update ${GITHUB_SHA}"\
          -e GH_PAT=${{ secrets.CR_PAT }}\
          ghcr.io/nokamoto/demo20-gitops-plugin:fd03cc4ecf506c8ca2156f9b3990fa12f6597cbc
